baseurl = "http://pcf-workshop.apps.pcf.cloud"
languageCode = "en-us"
title = "Cloud Foundry Workshop"



# theme="hyde-y"
theme="material-design"
# theme="hugo-bootstrap"
MetaDataFormat = "toml"
paginate = 21 # To specify a multiple of 3
disqusShortname = "" # optional
copyright = "© Copyright 2017 Pivotal Software, Inc. All Rights Reserved."

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    brand = "Pivotal"
    topline = "Do the right thing"
    footline = "code with <i class='fa fa-heart'></i>"
    tags = ["spring"]

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "Home"
    description = "West Corp · May 10 9:30 AM - 4:00 PM" # optional
    twitter = "pivotal" # optional
    customer = "west"
    # headerCover = "images/headerCover.png" # optional
    # footerCover = "images/footerCover.png" # optional
    googleAnalyticsUserID = "" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
